In [1]:
import numpy as np
np.random.seed(123)
x = np.round(np.random.normal(size = 20), 2)

In [3]:
x

array([-1.09,  1.  ,  0.28, -1.51, -0.58,  1.65, -2.43, -0.43,  1.27,
       -0.87, -0.68, -0.09,  1.49, -0.64, -0.44, -0.43,  2.21,  2.19,
        1.  ,  0.39])

In [2]:
x[((x > -2) & (x < -1)) | ((x>1)&(x<2))]

array([-1.09, -1.51,  1.65,  1.27,  1.49])

In [10]:
(x < 0).mean() , (x < 0).sum()

(0.55, 11)

In [12]:
np.abs(x).mean()

1.0335

In [4]:
np.max(np.abs(x))

2.43

In [15]:
np.argmax(np.abs(x))

6

In [18]:
x

array([-1.09,  1.  ,  0.28, -1.51, -0.58,  1.65, -2.43, -0.43,  1.27,
       -0.87, -0.68, -0.09,  1.49, -0.64, -0.44, -0.43,  2.21,  2.19,
        1.  ,  0.39])

In [17]:
x[np.argmax(np.abs(x))]

-2.43

In [19]:
x[np.argmax(np.abs(x-2))]

-2.43

In [5]:
np.modf(x)

(array([-0.09,  0.  ,  0.28, -0.51, -0.58,  0.65, -0.43, -0.43,  0.27,
        -0.87, -0.68, -0.09,  0.49, -0.64, -0.44, -0.43,  0.21,  0.19,
         0.  ,  0.39]),
 array([-1.,  1.,  0., -1., -0.,  1., -2., -0.,  1., -0., -0., -0.,  1.,
        -0., -0., -0.,  2.,  2.,  1.,  0.]))

In [23]:
np.abs(np.modf(x)[0])

array([0.09, 0.  , 0.28, 0.51, 0.58, 0.65, 0.43, 0.43, 0.27, 0.87, 0.68,
       0.09, 0.49, 0.64, 0.44, 0.43, 0.21, 0.19, 0.  , 0.39])

In [22]:
?np.modf

Call signature:  np.modf(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'modf'>
File:            ~/anaconda3/lib/python3.7/site-packages/numpy/__init__.py
Docstring:      
modf(x[, out1, out2], / [, out=(None, None)], *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Return the fractional and integral parts of an array, element-wise.

The fractional and integral parts are negative if the given number is
negative.

Parameters
----------
x : array_like
    Input array.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indic

In [7]:
np.where(x >= 0, 'nieujemny', 'ujemny')

array(['ujemny', 'nieujemny', 'nieujemny', 'ujemny', 'ujemny',
       'nieujemny', 'ujemny', 'ujemny', 'nieujemny', 'ujemny', 'ujemny',
       'ujemny', 'nieujemny', 'ujemny', 'ujemny', 'ujemny', 'nieujemny',
       'nieujemny', 'nieujemny', 'nieujemny'], dtype='<U9')

In [8]:
np.where(x < 1, 'maly', np.where(x > 1, 'duzy', 'sredni'))

array(['maly', 'sredni', 'maly', 'maly', 'maly', 'duzy', 'maly', 'maly',
       'duzy', 'maly', 'maly', 'maly', 'duzy', 'maly', 'maly', 'maly',
       'duzy', 'duzy', 'sredni', 'maly'], dtype='<U6')

In [15]:
x1 = np.r_[0:20]
x2 = np.r_[20:-1:-1]

In [16]:
np.r_[x1, x2]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,
        6,  5,  4,  3,  2,  1,  0])

In [20]:
np.where(x < 0, 0, np.where(x > 1, 1, x))

array([0.  , 1.  , 0.28, 0.  , 0.  , 1.  , 0.  , 0.  , 1.  , 0.  , 0.  ,
       0.  , 1.  , 0.  , 0.  , 0.  , 1.  , 1.  , 1.  , 0.39])

In [25]:
w = np.r_[1, 0, 0, 0, 1, 1]
y = np.r_[0, 0, 1, 0, 0, 1]

In [31]:
# ERR
(w == y).mean()

0.5

In [32]:
# MSE
(np.abs(w - y)**2).mean()

0.5

In [33]:
# RMSE
np.sqrt((np.abs(w - y)**2).sum()) / w.shape[0]

0.28867513459481287

In [34]:
# MAD
np.abs(w - y).mean()

0.5

In [52]:
def mc_pi(n):
    x = np.random.rand(n)
    y = np.random.rand(n)
    return 4 * (x**2 + y**2 <= 1).mean()

In [60]:
mc_pi(100000)

3.14284

In [61]:
np.r_[[mc_pi(100000) for _ in range(1000)]].mean()

3.1418740400000003

In [66]:
mc_pi(200000000)

3.14149528

In [102]:
l = []
for i in range(1000):
    l.append((np.random.randint(1,7, size=(3,20000)).sum(axis=0) < 6).mean())
np.r_[l].mean()

0.04635285

In [104]:
10/216

0.046296296296296294

In [105]:
n = 5
p = 3
X = np.random.rand(n, p)

In [127]:
X

array([[0.79366098, 0.62398367, 0.84326396],
       [0.38496003, 0.53262274, 0.41703362],
       [0.09429494, 0.23538476, 0.87220062],
       [0.47797523, 0.15918131, 0.00774526],
       [0.52313869, 0.57143285, 0.27208939]])

In [126]:
X.min(axis = 0)

array([0.09429494, 0.15918131, 0.00774526])

In [129]:
np.vstack((X.min(axis = 0), X.max(axis=0)))

array([[0.09429494, 0.15918131, 0.00774526],
       [0.79366098, 0.62398367, 0.87220062]])

In [135]:
np.c_[X.min(axis = 0), X.max(axis=0)]

array([[0.09429494, 0.79366098],
       [0.15918131, 0.62398367],
       [0.00774526, 0.87220062]])

In [131]:
np.c_[X.min(axis = 0), X.max(axis=0)].T

array([[0.09429494, 0.15918131, 0.00774526],
       [0.79366098, 0.62398367, 0.87220062]])

In [147]:
(X - X.mean(axis = 0)) / X.std(axis=0)

array([[ 1.50084146,  1.05350981,  1.08199086],
       [-0.30935855,  0.57096506, -0.19622607],
       [-1.59675937, -0.998969  ,  1.16876867],
       [ 0.10262023, -1.40145586, -1.42363591],
       [ 0.30265622,  0.77594999, -0.63089754]])