In [1]:
import numpy as np
np.random.seed(123)
x = np.round(np.random.normal(size = 20), 2)

In [7]:
x[((x > -2) & (x < -1)) | ((x>1)&(x<2))]

array([-1.09, -1.51,  1.65,  1.27,  1.49])

In [10]:
(x < 0).mean() , (x < 0).sum()

(0.55, 11)

In [12]:
np.abs(x).mean()

1.0335

In [15]:
np.argmax(np.abs(x))

6

In [18]:
x

array([-1.09,  1.  ,  0.28, -1.51, -0.58,  1.65, -2.43, -0.43,  1.27,
       -0.87, -0.68, -0.09,  1.49, -0.64, -0.44, -0.43,  2.21,  2.19,
        1.  ,  0.39])

In [17]:
x[np.argmax(np.abs(x))]

-2.43

In [19]:
x[np.argmax(np.abs(x-2))]

-2.43

In [23]:
np.abs(np.modf(x)[0])

array([0.09, 0.  , 0.28, 0.51, 0.58, 0.65, 0.43, 0.43, 0.27, 0.87, 0.68,
       0.09, 0.49, 0.64, 0.44, 0.43, 0.21, 0.19, 0.  , 0.39])

In [22]:
?np.modf

Call signature:  np.modf(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'modf'>
File:            ~/anaconda3/lib/python3.7/site-packages/numpy/__init__.py
Docstring:      
modf(x[, out1, out2], / [, out=(None, None)], *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Return the fractional and integral parts of an array, element-wise.

The fractional and integral parts are negative if the given number is
negative.

Parameters
----------
x : array_like
    Input array.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indic